# Generated by Django 5.2.6 on 2025-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "newsid",
                    models.AutoField(
                        db_column="NewsID", primary_key=True, serialize=False
                    ),
                ),
                ("publishdate", models.DateField(db_column="PublishDate")),
                ("url", models.CharField(db_column="URL", max_length=100)),
                ("summary", models.CharField(db_column="Summary", max_length=300)),
            ],
            options={
                "db_table": "News",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "News_Tag",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tagid",
                    models.AutoField(
                        db_column="TagID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tagname",
                    models.CharField(db_column="TagName", max_length=50, unique=True),
                ),
                ("type", models.IntegerField(db_column="Type")),
            ],
            options={
                "db_table": "Tag",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="UserID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(db_column="UserName", max_length=50, unique=True),
                ),
                ("password", models.CharField(db_column="PassWord", max_length=50)),
                (
                    "major",
                    models.CharField(
                        blank=True, db_column="Major", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visittimes", models.IntegerField(db_column="VisitTimes")),
            ],
            options={
                "db_table": "User_Tag",
                "managed": False,
            },
        ),
    ]
