CREATE DATABASE IF NOT EXISTS NewsManagement;
USE NewsManagement;

CREATE TABLE IF NOT EXISTS User (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  UserName VARCHAR(50) NOT NULL UNIQUE,
  PassWord VARCHAR(50) NOT NULL,
  Major VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS News (
  NewsID INT PRIMARY KEY AUTO_INCREMENT,
  PublishDate DATE NOT NULL,
  URL VARCHAR(100) NOT NULL,
  Summary VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tag (
  TagID INT PRIMARY KEY AUTO_INCREMENT,
  TagName VARCHAR(50) NOT NULL UNIQUE,
  Type TINYINT(1) NOT NULL -- 0代表source，1代表info
);

CREATE TABLE IF NOT EXISTS News_Tag(
    NewsID INT NOT NULL,
    TagID INT NOT NULL,
    PRIMARY KEY (NewsID, TagID),
    FOREIGN KEY (NewsID) 
    REFERENCES News(NewsID) ON DELETE CASCADE,
    FOREIGN KEY (TagID) 
    REFERENCES Tag(TagID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS User_Tag(
    UserID INT NOT NULL,
    TagID INT NOT NULL,
    VisitTimes INT DEFAULT 0,
    PRIMARY KEY (UserID, TagID),
    FOREIGN KEY (UserID) 
    REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (TagID) 
    REFERENCES Tag(TagID) ON DELETE CASCADE
);